### ISSUE TITLE
[QUESTION] How and why do you split your operations folder into manifests and releases?

### ISSUE THREAD

**Issue by ghost** [mfamador/gitops-demo-multitenant#2]
Hey Marco, I've watched your DevOps Porto meetup and was trying to understand how to setup a cluster managed like this.

But I'm not understanding why do you split the operations folder into manifests and releases. I've only noticed that manifests run after the releases.. Could you explain that?

Thanks,
Serpa

**Comment by mfamador** [comment]
Hey @serpa-dystematic ! 
I split the operations folder basically in two Kustomizations, because some resources (Gateway, Prometheus, etc.) are dependent on some CRDs to exist and which are only created when their Helm Releases are installed. If I'd put everything in the same Kustomization it'd fail.
Then I create a dependency in operations-manifests Kustomization to the operations-releases Kustomization which installs the Helm Releases that create the needed CRD and afterwards the dependent custom resources. It should have a health probe to guarantee that the helm releases were already installed, btw. One of these days I'll add it :)
Hope it helped.

**Comment by ghost** [comment]
So it's just a matter of dependencies and order, perfect!

That helped, thanks a lot! 🙌
